repos:
# Official repo for the clang-format hook
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v18.1.8'
  hooks:
  - id: clang-format
    types_or: [c, c++]
    exclude: "include/json.hpp"
    