repos:
# Official repo for the clang-format hook
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-xml
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: trailing-whitespace
# black repo for python formatting
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
# clang-format for C/C++ formatting
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.2
    hooks:
    -   id: clang-format
        args: ['--style=file']
        exclude: "include/json.hpp"
        types_or: [c++]
