name: FANS CI
on:
  workflow_dispatch:

env:
  FANS_DIR: /FANS
  FANS_IMG: unistuttgartdae/fans-ci
  FANS_BUILD_DIR: build

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Pull Docker image
        run: docker pull --platform linux/${{ matrix.arch }} $FANS_IMG

      - name: Build FANS
        run: |
          docker run --rm --name fans \
            --platform linux/${{ matrix.arch }} \
            -v /etc/localtime:/etc/localtime:ro \
            -v /etc/timezone:/etc/timezone:ro \
            -v ${{ github.workspace }}:${FANS_DIR} \
            -e FANS_DIR=${FANS_DIR} \
            $FANS_IMG \
            bash ${FANS_DIR}/.github/workflows/build.sh ${FANS_BUILD_DIR}

      - name: Package FANS
        run: |
          docker run --rm --name fans \
            --platform linux/${{ matrix.arch }} \
            -v /etc/localtime:/etc/localtime:ro \
            -v /etc/timezone:/etc/timezone:ro \
            -v ${{ github.workspace }}:${FANS_DIR} \
            -e FANS_DIR=${FANS_DIR} \
            $FANS_IMG \
            bash -c "cd ${FANS_DIR}/${FANS_BUILD_DIR} && cpack -G \"DEB\""

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: fans-packages-${{ matrix.arch }}
          path: ${{ github.workspace }}/${FANS_BUILD_DIR}/packages/*.deb

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push fans image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: unistuttgartdae/fans:latest
          target: fans
          args: BUILD_DIR=${FANS_BUILD_DIR}
