name: clang-format Check
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: '.'
        exclude: 'include/json.hpp'
        extensions: 'h,cpp'
        clangFormatVersion: 13
        inplace: true
