name: Build and Push Docker Images

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build fans image
        run: docker build --target=fans -t unistuttgartdae/fans -f docker/Dockerfile .

      - name: Push fans image
        run: docker push unistuttgartdae/fans

      - name: Build fans_dev image
        run: docker build --target=fans_dev -t unistuttgartdae/fans-dev -f docker/Dockerfile .

      - name: Push fans_dev image
        run: docker push unistuttgartdae/fans-dev
