name: Build and Push FANS helper images

on: workflow_dispatch

jobs:
  build-and-push:
    strategy:
      matrix:
        ubuntu-version: [noble, jammy, focal]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push fans_ci image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: unistuttgartdae/fans-ci-${{ matrix.ubuntu-version }}:latest
          target: fans_ci
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu-version }}

      - name: Build and push fans_dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: unistuttgartdae/fans-dev-${{ matrix.ubuntu-version }}:latest
          target: fans_dev
          build-args: UBUNTU_VERSION=${{ matrix.ubuntu-version }}

